services:
  links_api:
    build: src/links_api
    ports: 
      - "80:80"
    networks: 
      - main
  video_api:
    build: src/video_api
    ports:
      - "81:81"
    networks:
      - main  
    volumes:
      - shared:/shared
  pipeline:
    build: src/pipeline
    ports:
      - "82:82"
    networks:
      - main
    depends_on:
      - links_api
      - video_api
    volumes:
    - shared:/shared
  dashboard:
    build: src/dashboard
    ports: 
      - "8501:8501"
    networks:
      - main
networks:
  main:
volumes:
  shared: